### ISSUE TITLE
Shopify Payments iDeal Pending.Onboarding Verification wait time

### ISSUE THREAD

**Issue by SarahRoseO** [sharpaypal/financial-services-support#55]
#### Give a TLDR of what you're trying to solve.
Merchants are experiencing longer than 10 minute wait times for the verification of iDeal, when setting it up through Shopify Payments. 

#### Do you have an idea on what the process should be? If so, please share. 
Merchants should be verified successfully within the 10 minute time frame. If this is not possible, accurate expectations should be set when it comes to the timeframe.

#### Why is this important to address? 
Better merchant experience. There is an inconsistency with the message provided, and how the system is functioning.

#### What team(s) does this affect? Who are the possible stakeholders?
Financial Support Services, Stripe, the Merchant 

#### Please include any relevant Githubs, GuruCards, tickets, examples etc. 

[![alt](https://screenshot.click/10-10-rnxin-a7twf.jpg)](https://screenshot.click/10-10-rnxin-a7twf.jpg)

[![alt](https://screenshot.click/10-10-entj0-cbl04.jpg)](https://screenshot.click/10-10-entj0-cbl04.jpg)
@anyacasey @deborahisaac @sharpaypal

**Comment by deborahisaac** [comment]
I suggested Sarah-Rose post this to our project board because it ties into the work that we're doing with Stripe re: LPMs and onboarding times. A pathway forward could be.

1. Gather more data on how long these are taking on average. Sarah-Rose was collecting cases here and we could possibly reach out to the devs as well: https://docs.google.com/spreadsheets/d/1uS1yr4LWJ40Zk4o7Bj-th3cSHI6TYac-56GX0BEFIo4/edit?ts=5d9f6b0e#gid=0 .
2. Reach out to Stripe for more context on how long it should be taking.
3. If there's a significant mismatch and it's taking longer than 10 minutes, we could potentially look into updating the messaging.

This might also be related to this: https://github.com/Shopify/shopify/issues/217343

**Comment by anyacasey** [comment]
**Update October 11th:**

- Stripe have confirmed [here](https://shopify.zendesk.com/agent/tickets/14545817) that 10 minutes is the correct timeframe for iDEAL onboarding, assuming all required information is present and correct

- Most of the cases we have seen look like [this issue](https://github.com/Shopify/shopify/issues/217343); iDEAL is active on Stripe's end, and we need to re-import capabilities on our end

- More cases and updates for each have been added to the [spreadsheet](https://docs.google.com/spreadsheets/d/1uS1yr4LWJ40Zk4o7Bj-th3cSHI6TYac-56GX0BEFIo4/edit?ts=5d9f6b0e#gid=0)

- Awaiting further insight/ instruction from Alex [here](https://github.com/Shopify/shopify/issues/217343)

**Potential next steps:**

- Create a separate GitHub issue for iDEAL cases
- Instruct FSS team to try re-importing capabilities for new cases & add to spreadsheet

**Comment by anyacasey** [comment]
**Trello update to team:** https://trello.com/c/SEhqc8RO
